apiVersion: v1
kind: Service
metadata:
  name: deepadeploy
  namespace: deepa-app
spec:
  selector:
    app: deepadeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

